package writer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/quickcli/quick/internal/config"
	codexmerge "github.com/quickcli/quick/internal/config_merge/codex"
	"github.com/quickcli/quick/internal/login"
)

// codexConfigDir returns ~/.codex on all platforms.
func codexConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".codex")
}

// WriteCodex updates ~/.codex/config.toml and ~/.codex/auth.json for configs
// that have codex scope.
func WriteCodex(configs []config.Config) error {
	if err := os.MkdirAll(codexConfigDir(), 0o700); err != nil {
		return fmt.Errorf("create .codex dir: %w", err)
	}

	// Pick the last codex-scoped config as active.
	var active *config.Config
	for i := range configs {
		if configs[i].HasCodexScope() {
			active = &configs[i]
		}
	}
	if active == nil {
		return nil
	}

	if err := writeCodexConfig(configs, active); err != nil {
		return err
	}
	return writeCodexAuth(active)
}

func writeCodexConfig(configs []config.Config, active *config.Config) error {
	path := filepath.Join(codexConfigDir(), "config.toml")

	// Build the QuickCLI-managed portion.
	var managed strings.Builder
	managed.WriteString(fmt.Sprintf("model_provider = %q\n", active.Name))
	if active.Model != "" {
		managed.WriteString(fmt.Sprintf("model = %q\n", active.Model))
	}
	reasoningEffort := active.ReasoningEffort
	if reasoningEffort == "" {
		reasoningEffort = "high"
	}
	managed.WriteString(fmt.Sprintf("model_reasoning_effort = %q\n", reasoningEffort))
	if active.ModelVerbosity != "" {
		managed.WriteString(fmt.Sprintf("model_verbosity = %q\n", active.ModelVerbosity))
	}
	managed.WriteString("disable_response_storage = true\n")
	managed.WriteString("\n")

	for _, c := range configs {
		if !c.HasCodexScope() {
			continue
		}
		displayName := c.DisplayName
		if displayName == "" {
			displayName = c.Name
		}
		managed.WriteString(fmt.Sprintf("[model_providers.%s]\n", c.Name))
		managed.WriteString(fmt.Sprintf("name = %q\n", displayName))
		if c.BaseURL != "" {
			managed.WriteString(fmt.Sprintf("base_url = %q\n", c.BaseURL))
		}
		wireAPI := c.WireAPI
		if wireAPI == "" {
			wireAPI = "responses"
		}
		managed.WriteString(fmt.Sprintf("wire_api = %q\n", wireAPI))

		// requires_openai_auth and env_key are mutually exclusive.
		switch {
		case c.AuthMethod == "chatgpt":
			managed.WriteString("requires_openai_auth = true\n")
		case c.APIKey != "":
			managed.WriteString("requires_openai_auth = true\n")
		}
		managed.WriteString("\n")
	}

	// Preserve sections from the existing config.toml that are NOT managed by
	// QuickCLI (e.g. [projects.*], [windows], [history], etc.).
	// We keep any TOML section that doesn't start with [model_providers.
	preserved := preservedSections(path)

	// If the active config carries extra Codex TOML from a template, merge it
	// into the preserved (user) sections.  QuickCLI-owned keys are stripped
	// from the template content first so the managed block always wins.
	if active.CodexTomlContent != "" {
		filtered, filterErr := codexmerge.FilterOwned(active.CodexTomlContent)
		if filterErr == nil && filtered != "" {
			if merged, mergeErr := codexmerge.Merge(preserved, filtered); mergeErr == nil {
				preserved = merged
			}
		}
	}

	result := managed.String()
	if preserved != "" {
		result += preserved
	}

	if err := os.WriteFile(path, []byte(result), 0o600); err != nil {
		return fmt.Errorf("write codex config.toml: %w", err)
	}
	return nil
}

// preservedSections reads the existing config.toml and returns all TOML section
// blocks that QuickCLI does not own (i.e. not top-level scalar keys and not
// [model_providers.*] tables).
func preservedSections(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return "" // file doesn't exist yet — nothing to preserve
	}

	lines := strings.Split(string(data), "\n")
	var out strings.Builder
	inForeign := false // true while inside a non-model_providers section

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Detect section headers.
		if strings.HasPrefix(trimmed, "[") {
			if strings.HasPrefix(trimmed, "[model_providers.") {
				// QuickCLI-owned — skip this section.
				inForeign = false
				continue
			}
			// Any other section (e.g. [projects.*], [windows]) — preserve it.
			inForeign = true
		}

		if inForeign {
			out.WriteString(line + "\n")
		}
		// Lines before any section header (top-level scalars like model_provider,
		// model, model_reasoning_effort, etc.) are always regenerated by QuickCLI
		// and intentionally NOT preserved.
	}

	return strings.TrimRight(out.String(), "\n") + "\n"
}

// writeCodexAuth updates auth.json to match the chosen config's auth method:
//
//   - chatgpt  → tokens were written by the login flow; nothing to do here.
//   - api_key  → write the key AND set auth_mode="apikey", clearing any
//                stale chatgpt auth_mode that would cause token-refresh errors.
//   - anything else (local/no-auth providers) → clear auth_mode so Codex
//                doesn't try to refresh a token that no longer applies.
func writeCodexAuth(c *config.Config) error {
	switch {
	case c.AuthMethod == "chatgpt":
		// Tokens already in auth.json from the login flow — leave them alone.
		return nil
	case c.APIKey != "":
		// WriteAPIKey also sets auth_mode="apikey", overwriting any "chatgpt" remnant.
		return login.WriteAPIKey(codexConfigDir(), c.APIKey)
	default:
		// No auth needed (e.g. Ollama, LM Studio).
		// Clear auth_mode so Codex doesn't attempt OAuth token refresh.
		return login.ClearAuthMode(codexConfigDir())
	}
}
