package template

// builtinTemplates are templates bundled directly into the binary.
// They are used when the remote registry is unavailable or the registry
// repo has not been set up yet.
var builtinTemplates = []Template{
	{
		ID:              "openai",
		DisplayName:     "OpenAI (official)",
		Scope:           []string{"codex"},
		BaseURL:         "https://api.openai.com/v1",
		APIKey:          `${--:"OpenAI API Key":""}`,
		Model:           `${--:"Default model":"gpt-4o"}`,
		WireAPI:         "responses",
		AuthMethod:      "api_key",
		ReasoningEffort: `${--:"Reasoning effort (minimal/low/medium/high/xhigh)":"high"}`,
		DocsURL:         "https://platform.openai.com/docs",
	},
	{
		ID:          "amethyst",
		DisplayName: "Amethyst API",
		Scope:       []string{"codex"},
		BaseURL:     "https://api.amethyst.ltd/v1",
		APIKey:      `${--:"Amethyst API Key":""}`,
		Model:       `${--:"Default model":"gpt-5.4"}`,
		WireAPI:     "responses",
		AuthMethod:  "api_key",
		DocsURL:     "https://amethyst.ltd",
	},
	{
		ID:          "anthropic",
		DisplayName: "Anthropic (official)",
		Scope:       []string{"claudecode"},
		BaseURL:     "https://api.anthropic.com",
		APIKey:      `${--:"Anthropic API Key":""}`,
		Model:       `${--:"Default model":"claude-sonnet-4-5"}`,
		WireAPI:     "chat",
		AuthMethod:  "api_key",
		DocsURL:     "https://docs.anthropic.com",
	},
	{
		ID:          "privnode",
		DisplayName: "Privnode",
		Scope:       []string{"codex", "claudecode"},
		BaseURL:     `${--:"Privnode base URL":"https://privnode.com/v1"}`,
		APIKey:      `${--:"Privnode API Key":""}`,
		Model:       `${--:"Default model":"gpt-5-codex"}`,
		WireAPI:     "responses",
		AuthMethod:  "api_key",
		DocsURL:     "https://privnode.com/docs",
	},
	{
		ID:          "azure-openai",
		DisplayName: "Azure OpenAI",
		Scope:       []string{"codex"},
		BaseURL:     `${--:"Azure endpoint (e.g. https://<name>.openai.azure.com/openai/deployments/<deploy>)":""}`,
		APIKey:      `${--:"Azure API Key":""}`,
		Model:       `${--:"Deployment / model name":"gpt-4o"}`,
		WireAPI:     "chat",
		AuthMethod:  "api_key",
		DocsURL:     "https://learn.microsoft.com/azure/ai-services/openai/",
	},
	{
		ID:          "ollama",
		DisplayName: "Ollama (local)",
		Scope:       []string{"codex"},
		BaseURL:     `${--:"Ollama base URL":"http://localhost:11434/v1"}`,
		APIKey:      "ollama",
		Model:       `${--:"Model name":"llama3"}`,
		WireAPI:     "chat",
		AuthMethod:  "api_key",
		DocsURL:     "https://ollama.com",
	},
	{
		ID:          "lmstudio",
		DisplayName: "LM Studio (local)",
		Scope:       []string{"codex"},
		BaseURL:     `${--:"LM Studio base URL":"http://localhost:1234/v1"}`,
		APIKey:      "lm-studio",
		Model:       `${--:"Model identifier":""}`,
		WireAPI:     "chat",
		AuthMethod:  "api_key",
		DocsURL:     "https://lmstudio.ai",
	},
	{
		ID:          "bedrock",
		DisplayName: "Amazon Bedrock",
		Scope:       []string{"claudecode"},
		BaseURL:     "",
		APIKey:      "",
		Model:       `${--:"Model ID (e.g. anthropic.claude-sonnet-4-5-20251001-v1:0)":""}`,
		WireAPI:     "chat",
		AuthMethod:  "aws",
		RequiredEnvs: []string{
			"CLAUDE_CODE_USE_BEDROCK=1",
			"AWS_REGION",
			"AWS_ACCESS_KEY_ID",
			"AWS_SECRET_ACCESS_KEY",
		},
		DocsURL: "https://docs.anthropic.com/en/docs/claude-code/bedrock-vertex",
	},
}
